### ISSUE TITLE
License and readme feature

### ISSUE THREAD

**Issue by katiemcculloch** [liquidata-inc/dolt#276]
This issue is to track the tasks for License and Readme feature in dolt (the feature branch is #222). LICENSE.md and README.md (what we're calling dolt docs) are 2 files that can be modified, staged and committed in a dolt repository. You can edit the files like usual, in a text editor or vim, and then stage and commit the changes.  

To take advantage of the dolt table storage, the docs table will be stored in the existing table map that holds all the dolt tables on a root value. This table is called `dolt_docs` (it will not be exposed directly through dolt commands): 

```
+------------+---------------------+
| doc_name   | doc_text            |
+------------+---------------------+
| LICENSE.md |                     |
| README.md  | This is my readme.  |
+------------+--------------------+
```

Tasks: 
- [x] `dolt status` (#222 and #242)
- [x] `dolt add .` (#242) 
     - Exception:  allow `dolt add <doc>` when conflicts need to be resolved
- [x] `dolt add <doc>` (#247)
- [x] `dolt reset .` (#263)
- [x] `dolt reset <doc>` (#263)
- [x] `dolt diff` (#278)
- [x] `dolt diff <doc>` (#278)
- [x] `dolt checkout <doc>` (#299)
- [x] `dolt merge <doc>` with no conflicts (FF merge) (#299)
- [x] `dolt merge <doc>` with conflicts that need to be resolved (#299)
- [x] `dolt merge <doc>` with conflicts that are auto resolved (#299)
- [x] Removing dolt_docs from certain dolt commands (we will eventually add it back to read-only commands):
     - [x] `dolt table *` (#279)
     - [x] `dolt schema *` (#279)
     - [x] `dolt add` (#279)
     - [x] `dolt diff` (#279)
     - [x] `dolt ls` (#279)
     - [x] `dolt reset` (#279)
     - [x] `dolt sql` (#280)

**Comment by timsehn** [comment]
Released in 0.12
